language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules

before_install:
  - sudo pip install awscli
  - ls /usr/local/bin/
  - which aws
  - npm set progress=false

script:
- npm run build
- npm test

before_deploy:
  - cd trip-pin-points-frontend
  - echo $(git rev-parse --short HEAD) >> /tmp/version
  - zip -0 /tmp/travisci-$(cat /tmp/version).zip -r build Dockerfile nginx.conf
  - chmod +x deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh
    on:
      branch: master

env:
  matrix:
  - secure: CP4bkhddtcMqFRflh2CgncOXgXHyz4MPCVN7bPCpFfJ9rDDxc0baXCs2s45L1vvWi3ZaEPob/BIq1Wj+GZQzuUAErC1Y82k7k0kyDrx83Fg0L3PyqPy81BcjV5bvCDGkxZWBLBHZPPPgu8smRCb9k3ZlkfaWjizhp8OYdgY8kgoEbhtQGfwYmdOltusFncQ5p3zqH23SgMqME0GjiWX0swGEW4fbGB7BDKxsZMF0bo3TSeYsIjLwuOeXVT33PH63MpkYUEyBQHlVo8X0ZrqWpBn2ra+BS5WcfoWnm2YuzHTJ2kM/4fujo3FRX1LfSI4wzs+MwWZY6JjukqjGsXrHirOlmj8K0HPDY462zhc9cTrZeKNs3sYr4g6iRv13M+AMpOu3IqSgcRjevPH3Oi3ISLAMWswbG1C1VA00IqIW0pknSqrRVZTvvKKCPAPV3aJM5LiPTZnrnLxjtd+PRATAY3z3vz1OWuo5JDTBxKorCfM9LMO+osu/q1DIbg9/t8lR32r1F11obTLLJLI/O+Is6CpK4YJO7oAKFCc6fcIbAdbKm9cTT6mYNOJUEPBpQbBcTeIDfcphy9W5LNlQBIl0G0VrR5l4HcY/jdojzf6PKXFTBVjMbCBaqo6S4Fi8jtsA1KrtW0lG6J75WcTkYXQC3AWhvDOhXHBzlsEzQxUUDH0=
  - secure: PljqPq0U+vv8ERxBAkiXQPtwxGKr4AW6mu/YeZBQThIdINdaaoR5QGyct2FMvIH75cxn4A5R4vvDjTlRsxCdi+0CgOenZcRJFnxMed9M+r4oESVAWrafKDJWmgACDREnRJpQOqsB4b72xXRmBk4IgzHFm3oeH2aOea0v85RWIFMAH8iRc9AtoI2KLkH7vXmUTR7DVpMTUKaCZQi3twVrqDh1ik0OQO/+HgMOX5ni6xw0bFM4dGmsiF7u4noDRvpH7aScs9oaEVKaUYArcd40t4s6F2aWZYjQzPgEC7kmAFPIcypJG+UgYFreO930BLfV/28uggleGhXQ0pWpuJdhhrhYcT1UeUfuZc+qzz+Uxw7rFCkZ+lg1nw70A/HCYoH2NBomxtJJVstYsPghOL9HOAfzrcQKKOs9z+Ej0L5qI5hiUMvAOlhzLH8kJShSzzmpOFEcThL2/rD87Fnh0Kq3PCdgs0xlIPvkT+kgg278JLMI2FnP7ef5j2W7iUdwk6I3zrEmC26smpzJMJU2M67H/vZGVTNjCuwZONI+wMtECd5Xm05fhrLX0iLb7ZR8m8k3gyEekjeHGjxjx8u3Dy/vfx51TVRxeBmGjZ8O1+HQDFMATBpdlKwTLtMnn0P8O+rMLJbogZ328rEkybxAYE+ZUNaPALqXwKlOHBpUTA8ltmQ=
  - secure: UiEhTiJu3OIhwSznvhj/s21ZfVo/QAww0UQEif0e+FIrJvj/OWGx0Y6NjoDuIncGPNfnSL2HhxSBKk766MOSATnQzRPPA6PpjYuftN+TrUObemIJZXnBRDepdcPvn1uy7bQJ+zXjTht1lc2ew/0VKgSgIlOPSctLmasTP6BMcVupBkdMTrSxOmxzGAqKebNTImvX0EQmCr70bsglj/zXjji4qGX1XMjGNKK7jkBi/hgqoPBaYaPNUI4MWfxbKIBsvvErqAieqVVIhdDeli43BXH1SmJZq68Qmc2phmN8N3BpxWs7PT/F5SUWXHlbmMQXqLAi5yF0fpRYfn2OzHDkGcLxx0+LkDuLRml7ACk+ClMeNwB0wZjNC2P9NkV9RFkvqsde2ezbfGnobk1nkX1K5XkX2xjgcxmcFiNMr7pStteRKnjIUobBrpGLOUPWehmdLLIJdM6wjlDzPFVPjQ8uAYFerpV9ob6GpB2iMn80nP+q09rvW1fvih7JvdewaqYLMryOMAkFURwePQYGw4Ywlylrbj9tcUXK+ctS0BLS9TZVifgAZlw6P/m9ZDn+VR/IzDVNAgv+5RDnYHib9f1nPBw7272P6UCbYxGQmnLw401mhIHpxzj66NA8bZsE5MSZXmHAh9Y5hbQdAKO2Sj03FC1nGH5B7zHygLQFQ1rm4+U=
