language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AN/HDZHiIN9i4t+PPiHWM3vojUy1ky931YiOUqnoIWcDxHWgIrK8yGKTBv7FiXGu1DbButYLo2syWXhrwxRKt1YO/KMtNwj3LDE7JABYW6O/6+w6mnRqDwKC1m06TU40kEFjMTq9GEt51wW/Iat3gE3d6OtcjRX6wZnwtDHFy+W7Ip80omqZ6p6fGvWorQ+DGCfImeQEpZTb7pYwatD4nrZpj7TwcvUb0ShGoByKU8HuoW2OCGbuaLyNWNjywATIwEQVkrQbIP2jAhcnNEN0SXHAtX86Kb+AJEkwlwMW9vjdXFJEzo3OB6y8dOmBT3Ry2Qpa/dYh+bPMqeXARsxxqKXjrrpJXrJdbedE/HzhR7zyZx59q25mSmCvwx1hovTM5rBUABK6BDFfJfnZtnLAEwTAtp+qDQ9X//EI4IVZNIlKd2n7xSlUyERWIrsJiBrZXi/yQmNn3VCzNXKvTcYet8a5eqw2t2Gbm4aerDU5oNlLp5XKnppUfeR+/WcpKE56Tg5FwqFbCRvul3Q0j8jujej3XvNw/10UvrSdegO1kktciXxF3GPCtEGOnJ08vD/90g2/CXQYHT4dzW5w4pmnpn0oP5+aa0DLdfnOhuaBF95HYRm2mPJfE8TXTgsGpz6tvwgB7ZvAqa8g8MvaLgFwcjDI5ypxl8GVitzZZs5yjMU=
  secret_access_key:
    secure: KRXmhF4XcWk8UlgC0wYu0wt6d7mv2zbtOCJCV2xepeXPgDByPg5oRcTKRP2ZCLfpmHEM5xSyAJxqp4usa+EPW2PMNpK8joFqvSNTzAHH47m4iAy6T8uEEpnoUZ6FRNH/V6h5U8pEZ5LD9F0FKXpEM/vWqxPJxjrCyZrfbVZ6Ga3rQUM7G9QSoijC4XSX78ilYYjRh6QpJ70gW9uFjnJo9LOdHZN/P9LQb6xUW5adHe3ejztt20IZmWZdzmCPTOaiabQHziSEu4s6107jLJMH++IAMyUjbPumL4hI+kyLDk5f6Z5OETlrrUQSVMbXU2wM0CNh7WaMfwkUIynC+lMTQ9wuoto/5zL6xV2MEfiM12KtEKp8OWHjA8wuGDuY0pkTrNzfxPg3svgHoXry4KTjLKk7i5kaMzOijNEnNhvmPkSjttjIREVAlPGI4+4BSlpP9dGH7YEXjC+/C+wqk4kRVYAu1g+WgrMFYybA4Q3ramYk5MEw3OuzYYhT2do3ufd5tQZ9u7yiviZ3qbHVuQ7lltJBVNiaMU8EhvnFwKbymKz6NjBcNkjAdl0td1W0JTuPSR3JqS5gdVvEP6ijOEMRmcIHWQWI4kNrK9U4RfnTBmq7vLSRmGtGai7LOliwzB3Zq9DbZqo0gaM9qMn22hBqUvXLguQLO3B7fqUVAAF7RkI=
  region: sa-east-1
  app: trip-pin-points-frontend
  env: TripPinPointsFrontend-env
  bucket_name: elasticbeanstalk-sa-east-1-877463950700
  skip_cleanup: true
env:
  matrix:
    secure: CP4bkhddtcMqFRflh2CgncOXgXHyz4MPCVN7bPCpFfJ9rDDxc0baXCs2s45L1vvWi3ZaEPob/BIq1Wj+GZQzuUAErC1Y82k7k0kyDrx83Fg0L3PyqPy81BcjV5bvCDGkxZWBLBHZPPPgu8smRCb9k3ZlkfaWjizhp8OYdgY8kgoEbhtQGfwYmdOltusFncQ5p3zqH23SgMqME0GjiWX0swGEW4fbGB7BDKxsZMF0bo3TSeYsIjLwuOeXVT33PH63MpkYUEyBQHlVo8X0ZrqWpBn2ra+BS5WcfoWnm2YuzHTJ2kM/4fujo3FRX1LfSI4wzs+MwWZY6JjukqjGsXrHirOlmj8K0HPDY462zhc9cTrZeKNs3sYr4g6iRv13M+AMpOu3IqSgcRjevPH3Oi3ISLAMWswbG1C1VA00IqIW0pknSqrRVZTvvKKCPAPV3aJM5LiPTZnrnLxjtd+PRATAY3z3vz1OWuo5JDTBxKorCfM9LMO+osu/q1DIbg9/t8lR32r1F11obTLLJLI/O+Is6CpK4YJO7oAKFCc6fcIbAdbKm9cTT6mYNOJUEPBpQbBcTeIDfcphy9W5LNlQBIl0G0VrR5l4HcY/jdojzf6PKXFTBVjMbCBaqo6S4Fi8jtsA1KrtW0lG6J75WcTkYXQC3AWhvDOhXHBzlsEzQxUUDH0=
